language: csharp

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      dotnet: 2.1.502
      mono: none
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 2.1.502
      mono: none

branches:
  only:
    - master
script:
  - ulimit -n 2048
  - dotnet restore "src\Hangfire.LiteDB" 
  - dotnet build "src\Hangfire.LiteDB" -f netstandard2.0
  - dotnet restore "test\Hangfire.LiteDB.Test"
  - dotnet build "test\Hangfire.LiteDB.Test" -c Release
  - dotnet test "test\Hangfire.LiteDB.Test\Hangfire.LiteDB.Test.csproj" --configuration Release --no-build
  